### ISSUE TITLE
Universal slashes

### ISSUE THREAD

**Issue by Polm90** [jfoclpf/cordova-import-npm#1]
Hi,
when you initialize the package, it adds the hook in the config file. However, on Windows, it writes the hook path using "\": if you later compile the project on a MacOS (or Linux), the hook will be skipped because it doesn't found the hook.

You should always use the "/" as path separator: it works both on Windows and MacOS (or Linux).

Thank you!

**Comment by jfoclpf** [comment]
Thanks, I use always Ubuntu, but thanks for the pointing that out

Did you run also the config?

```
npx setup-cordova-import-npm
```

you need to install the package and after run the config to install the hook on `config.xml`

That path is formed [here](https://github.com/jfoclpf/cordova-import-npm/blob/master/scripts/setupCordovaImportNpm.js#L12), with this line

```js
const importNpmPackagesFilePath = path.join('node_modules', 'cordova-import-npm', 'scripts', 'importNpmPackages.js')
```

The result is a string: `"node_modules/cordova-import-npm/scripts/importNpmPackages.js"
`

**Comment by jfoclpf** [comment]
Ah, now I understand what you mean :)

**Comment by Polm90** [comment]
@jfoclpf this is one of those rare cases in which you should not use path.join, but directly the "/" string :D

Yes, I've used the npx command, so I've found the issue ;)

**Comment by jfoclpf** [comment]
Thanks @Polm90 
[I already amended it ](https://github.com/jfoclpf/cordova-import-npm/compare/4b9e58a5fbd6146eed6c77dd2f28bd6350bd946e..master)

I will publish to npm ASAP

**Comment by jfoclpf** [comment]
@Polm90 it's already published into npm

can you kindly test it in Windows now?
Thanks

**Comment by Polm90** [comment]
@jfoclpf I confirm it works now!

Thank you!

**Comment by jfoclpf** [comment]
Thanks for the feedback @Polm90 
have a great day
